// notification-api.ts
// Plugin → core notification emission helper (feature 006-05, ADR-035).
// Mirrors the emitEvent pattern in plugin-sdk.ts: an HTTP POST to
// /api/v1/notifications/emit authenticated with the plugin service identity
// (service token, falling back to the user JWT) via PluginHttp.

import { resolvePluginConfig } from './config.js';
import { PluginHttp } from './http.js';

import type { EmitNotificationInput, EmitNotificationResult } from './types.js';
import type { PluginConfig } from './types.js';

/**
 * Emit a notification to a tenant user via the core platform.
 * The type is automatically prefixed with `plugin.<slug>.`.
 * Resolves the same env fallbacks as PluginSDK (CORE_API_URL,
 * PLEXICA_SERVICE_TOKEN, PLEXICA_INSTALL_ID) so the standalone entry point
 * keeps the same identity/auth as emitEvent.
 *
 * @param config - Plugin configuration (same identity/auth as emitEvent)
 * @param input - Notification payload (userId, type, titleKey, …)
 * @returns The notificationId generated by core at emission (ADR-035 Decision 5)
 * @throws {ApiCallError} on non-2xx response
 */
export async function emitNotification(
  config: PluginConfig,
  input: EmitNotificationInput
): Promise<EmitNotificationResult> {
  const http = new PluginHttp(resolvePluginConfig(config));
  return http.emitNotification(input);
}
