import { readFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

// @ts-ignore - generated by `pnpm db:generate` before checks run.
import { PrismaClient as TenantPrismaClient } from '../../../prisma/generated/tenant-client/index.js';
import { prisma } from '../../lib/database.js';
import { toRealmName, toSchemaName } from '../../lib/tenant-schema-helpers.js';

import type { Prisma } from '@prisma/client';
import type { TenantContext } from '../../lib/tenant-context-store.js';

const MIGRATIONS_DIR = resolve(
  dirname(fileURLToPath(import.meta.url)),
  '../../../prisma/migrations'
);
const TENANT_MIGRATION_FILES = ['003_core_features/migration.sql'];

export interface SeedTenantResult {
  tenantContext: TenantContext;
  tenantId: string;
}

function buildTenantClient(schemaName: string): InstanceType<typeof TenantPrismaClient> {
  const baseUrl = process.env['DATABASE_URL'] ?? '';
  const tenantUrl = baseUrl.includes('?')
    ? `${baseUrl}&schema=${schemaName}`
    : `${baseUrl}?schema=${schemaName}`;
  return new TenantPrismaClient({ datasources: { db: { url: tenantUrl } } });
}

async function applyTenantMigrations(schemaName: string): Promise<void> {
  for (const relativePath of TENANT_MIGRATION_FILES) {
    const rawSql = readFileSync(resolve(MIGRATIONS_DIR, relativePath), 'utf8');
    const statements = rawSql
      .replace(/--.*$/gm, '')
      .trim()
      .split(';')
      .map((statement) => statement.trim())
      .filter((statement) => statement.length > 0);

    await prisma.$transaction(async (tx: Prisma.TransactionClient) => {
      await tx.$executeRawUnsafe(`SET LOCAL search_path TO "${schemaName}",public`);
      for (const statement of statements) await tx.$executeRawUnsafe(statement);
    });
  }
}

export async function seedTenant(slug: string): Promise<SeedTenantResult> {
  const schemaName = toSchemaName(slug);
  const realmName = toRealmName(slug);
  let tenant = await prisma.tenant.findUnique({ where: { slug } });

  if (tenant === null) {
    await prisma.$transaction(async (tx: Prisma.TransactionClient) => {
      const created = await tx.tenant.create({
        data: { slug, name: slug, status: 'active' },
      });
      tenant = created;
      await tx.$executeRawUnsafe(`CREATE SCHEMA IF NOT EXISTS "${schemaName}"`);
      await tx.tenantConfig.create({
        data: { tenantId: created.id, keycloakRealm: realmName },
      });
    });
    tenant = await prisma.tenant.findUnique({ where: { slug } });
    await applyTenantMigrations(schemaName);
  }

  if (tenant === null) throw new Error(`Failed to seed tenant: ${slug}`);
  return {
    tenantContext: {
      tenantId: tenant.id,
      slug: tenant.slug,
      schemaName,
      realmName,
    },
    tenantId: tenant.id,
  };
}

export async function cleanupTenant(slug: string): Promise<void> {
  const schemaName = toSchemaName(slug);
  try {
    await prisma.$executeRawUnsafe(`DROP SCHEMA IF EXISTS "${schemaName}" CASCADE`);
    const tenant = await prisma.tenant.findUnique({ where: { slug }, select: { id: true } });
    if (tenant) {
      await prisma.eventOutbox.deleteMany({ where: { tenantId: tenant.id } });
      await prisma.deadLetterQueue.deleteMany({ where: { tenantId: tenant.id } });
      await prisma.tenantEventKey.deleteMany({ where: { tenantId: tenant.id } });
    }
    await prisma.tenantConfig.deleteMany({ where: { tenant: { slug } } });
    await prisma.tenant.deleteMany({ where: { slug } });
  } catch {
    // Cleanup is best-effort because test fixtures use unique tenant slugs.
  }
}

export function buildTenantClientForCtx(
  tenantContext: TenantContext
): InstanceType<typeof TenantPrismaClient> {
  return buildTenantClient(tenantContext.schemaName);
}
