/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root';
import { Route as WorkspaceSettingsRouteImport } from './routes/workspace-settings';
import { Route as TeamRouteImport } from './routes/team';
import { Route as SettingsRouteImport } from './routes/settings';
import { Route as PluginsRouteImport } from './routes/plugins';
import { Route as PluginsPluginIdRouteImport } from './routes/plugins.$pluginId';
import { Route as MembersManagementRouteImport } from './routes/members-management';
import { Route as LoginRouteImport } from './routes/login';
import { Route as ActivityLogRouteImport } from './routes/activity-log';
import { Route as AuthErrorRouteImport } from './routes/auth/error';
import { Route as AuthCallbackRouteImport } from './routes/auth/callback';
import { Route as IndexRouteImport } from './routes/index';

const WorkspaceSettingsRoute = WorkspaceSettingsRouteImport.update({
  id: '/workspace-settings',
  path: '/workspace-settings',
  getParentRoute: () => rootRouteImport,
} as any);
const TeamRoute = TeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => rootRouteImport,
} as any);
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any);
const PluginsRoute = PluginsRouteImport.update({
  id: '/plugins',
  path: '/plugins',
  getParentRoute: () => rootRouteImport,
} as any);
const PluginsPluginIdRoute = PluginsPluginIdRouteImport.update({
  id: '/plugins/$pluginId',
  path: '/plugins/$pluginId',
  getParentRoute: () => rootRouteImport,
} as any);
const MembersManagementRoute = MembersManagementRouteImport.update({
  id: '/members-management',
  path: '/members-management',
  getParentRoute: () => rootRouteImport,
} as any);
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any);
const ActivityLogRoute = ActivityLogRouteImport.update({
  id: '/activity-log',
  path: '/activity-log',
  getParentRoute: () => rootRouteImport,
} as any);
const AuthErrorRoute = AuthErrorRouteImport.update({
  id: '/auth/error',
  path: '/auth/error',
  getParentRoute: () => rootRouteImport,
} as any);
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any);
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any);

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute;
  '/activity-log': typeof ActivityLogRoute;
  '/auth/callback': typeof AuthCallbackRoute;
  '/auth/error': typeof AuthErrorRoute;
  '/login': typeof LoginRoute;
  '/members-management': typeof MembersManagementRoute;
  '/plugins': typeof PluginsRoute;
  '/plugins/$pluginId': typeof PluginsPluginIdRoute;
  '/settings': typeof SettingsRoute;
  '/team': typeof TeamRoute;
  '/workspace-settings': typeof WorkspaceSettingsRoute;
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute;
  '/activity-log': typeof ActivityLogRoute;
  '/auth/callback': typeof AuthCallbackRoute;
  '/auth/error': typeof AuthErrorRoute;
  '/login': typeof LoginRoute;
  '/members-management': typeof MembersManagementRoute;
  '/plugins': typeof PluginsRoute;
  '/plugins/$pluginId': typeof PluginsPluginIdRoute;
  '/settings': typeof SettingsRoute;
  '/team': typeof TeamRoute;
  '/workspace-settings': typeof WorkspaceSettingsRoute;
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport;
  '/': typeof IndexRoute;
  '/activity-log': typeof ActivityLogRoute;
  '/auth/callback': typeof AuthCallbackRoute;
  '/auth/error': typeof AuthErrorRoute;
  '/login': typeof LoginRoute;
  '/members-management': typeof MembersManagementRoute;
  '/plugins': typeof PluginsRoute;
  '/plugins/$pluginId': typeof PluginsPluginIdRoute;
  '/settings': typeof SettingsRoute;
  '/team': typeof TeamRoute;
  '/workspace-settings': typeof WorkspaceSettingsRoute;
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths:
    | '/'
    | '/activity-log'
    | '/auth/callback'
    | '/auth/error'
    | '/login'
    | '/members-management'
    | '/plugins'
    | '/plugins/$pluginId'
    | '/settings'
    | '/team'
    | '/workspace-settings';
  fileRoutesByTo: FileRoutesByTo;
  to:
    | '/'
    | '/activity-log'
    | '/auth/callback'
    | '/auth/error'
    | '/login'
    | '/members-management'
    | '/plugins'
    | '/plugins/$pluginId'
    | '/settings'
    | '/team'
    | '/workspace-settings';
  id:
    | '__root__'
    | '/'
    | '/activity-log'
    | '/auth/callback'
    | '/auth/error'
    | '/login'
    | '/members-management'
    | '/plugins'
    | '/plugins/$pluginId'
    | '/settings'
    | '/team'
    | '/workspace-settings';
  fileRoutesById: FileRoutesById;
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute;
  ActivityLogRoute: typeof ActivityLogRoute;
  AuthCallbackRoute: typeof AuthCallbackRoute;
  AuthErrorRoute: typeof AuthErrorRoute;
  LoginRoute: typeof LoginRoute;
  MembersManagementRoute: typeof MembersManagementRoute;
  PluginsRoute: typeof PluginsRoute;
  PluginsPluginIdRoute: typeof PluginsPluginIdRoute;
  SettingsRoute: typeof SettingsRoute;
  TeamRoute: typeof TeamRoute;
  WorkspaceSettingsRoute: typeof WorkspaceSettingsRoute;
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/workspace-settings': {
      id: '/workspace-settings';
      path: '/workspace-settings';
      fullPath: '/workspace-settings';
      preLoaderRoute: typeof WorkspaceSettingsRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/team': {
      id: '/team';
      path: '/team';
      fullPath: '/team';
      preLoaderRoute: typeof TeamRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/settings': {
      id: '/settings';
      path: '/settings';
      fullPath: '/settings';
      preLoaderRoute: typeof SettingsRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/plugins': {
      id: '/plugins';
      path: '/plugins';
      fullPath: '/plugins';
      preLoaderRoute: typeof PluginsRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/plugins/$pluginId': {
      id: '/plugins/$pluginId';
      path: '/plugins/$pluginId';
      fullPath: '/plugins/$pluginId';
      preLoaderRoute: typeof PluginsPluginIdRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/members-management': {
      id: '/members-management';
      path: '/members-management';
      fullPath: '/members-management';
      preLoaderRoute: typeof MembersManagementRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/login': {
      id: '/login';
      path: '/login';
      fullPath: '/login';
      preLoaderRoute: typeof LoginRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/activity-log': {
      id: '/activity-log';
      path: '/activity-log';
      fullPath: '/activity-log';
      preLoaderRoute: typeof ActivityLogRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/auth/callback': {
      id: '/auth/callback';
      path: '/auth/callback';
      fullPath: '/auth/callback';
      preLoaderRoute: typeof AuthCallbackRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/auth/error': {
      id: '/auth/error';
      path: '/auth/error';
      fullPath: '/auth/error';
      preLoaderRoute: typeof AuthErrorRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/': {
      id: '/';
      path: '/';
      fullPath: '/';
      preLoaderRoute: typeof IndexRouteImport;
      parentRoute: typeof rootRouteImport;
    };
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ActivityLogRoute: ActivityLogRoute,
  AuthCallbackRoute: AuthCallbackRoute,
  AuthErrorRoute: AuthErrorRoute,
  LoginRoute: LoginRoute,
  MembersManagementRoute: MembersManagementRoute,
  PluginsRoute: PluginsRoute,
  PluginsPluginIdRoute: PluginsPluginIdRoute,
  SettingsRoute: SettingsRoute,
  TeamRoute: TeamRoute,
  WorkspaceSettingsRoute: WorkspaceSettingsRoute,
};
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>();
