/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root';
import { Route as LoginRouteImport } from './routes/login';
import { Route as AnalyticsRouteImport } from './routes/analytics';
import { Route as IndexRouteImport } from './routes/index';
import { Route as UsersIndexRouteImport } from './routes/users/index';
import { Route as TenantsIndexRouteImport } from './routes/tenants/index';
import { Route as PluginsIndexRouteImport } from './routes/plugins/index';

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any);
const AnalyticsRoute = AnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => rootRouteImport,
} as any);
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any);
const UsersIndexRoute = UsersIndexRouteImport.update({
  id: '/users/',
  path: '/users/',
  getParentRoute: () => rootRouteImport,
} as any);
const TenantsIndexRoute = TenantsIndexRouteImport.update({
  id: '/tenants/',
  path: '/tenants/',
  getParentRoute: () => rootRouteImport,
} as any);
const PluginsIndexRoute = PluginsIndexRouteImport.update({
  id: '/plugins/',
  path: '/plugins/',
  getParentRoute: () => rootRouteImport,
} as any);

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute;
  '/analytics': typeof AnalyticsRoute;
  '/login': typeof LoginRoute;
  '/plugins/': typeof PluginsIndexRoute;
  '/tenants/': typeof TenantsIndexRoute;
  '/users/': typeof UsersIndexRoute;
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute;
  '/analytics': typeof AnalyticsRoute;
  '/login': typeof LoginRoute;
  '/plugins': typeof PluginsIndexRoute;
  '/tenants': typeof TenantsIndexRoute;
  '/users': typeof UsersIndexRoute;
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport;
  '/': typeof IndexRoute;
  '/analytics': typeof AnalyticsRoute;
  '/login': typeof LoginRoute;
  '/plugins/': typeof PluginsIndexRoute;
  '/tenants/': typeof TenantsIndexRoute;
  '/users/': typeof UsersIndexRoute;
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths: '/' | '/analytics' | '/login' | '/plugins/' | '/tenants/' | '/users/';
  fileRoutesByTo: FileRoutesByTo;
  to: '/' | '/analytics' | '/login' | '/plugins' | '/tenants' | '/users';
  id: '__root__' | '/' | '/analytics' | '/login' | '/plugins/' | '/tenants/' | '/users/';
  fileRoutesById: FileRoutesById;
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute;
  AnalyticsRoute: typeof AnalyticsRoute;
  LoginRoute: typeof LoginRoute;
  PluginsIndexRoute: typeof PluginsIndexRoute;
  TenantsIndexRoute: typeof TenantsIndexRoute;
  UsersIndexRoute: typeof UsersIndexRoute;
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login';
      path: '/login';
      fullPath: '/login';
      preLoaderRoute: typeof LoginRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/analytics': {
      id: '/analytics';
      path: '/analytics';
      fullPath: '/analytics';
      preLoaderRoute: typeof AnalyticsRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/': {
      id: '/';
      path: '/';
      fullPath: '/';
      preLoaderRoute: typeof IndexRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/users/': {
      id: '/users/';
      path: '/users';
      fullPath: '/users/';
      preLoaderRoute: typeof UsersIndexRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/tenants/': {
      id: '/tenants/';
      path: '/tenants';
      fullPath: '/tenants/';
      preLoaderRoute: typeof TenantsIndexRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/plugins/': {
      id: '/plugins/';
      path: '/plugins';
      fullPath: '/plugins/';
      preLoaderRoute: typeof PluginsIndexRouteImport;
      parentRoute: typeof rootRouteImport;
    };
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AnalyticsRoute: AnalyticsRoute,
  LoginRoute: LoginRoute,
  PluginsIndexRoute: PluginsIndexRoute,
  TenantsIndexRoute: TenantsIndexRoute,
  UsersIndexRoute: UsersIndexRoute,
};
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>();
