// templates.ts
// Handlebars-style templates for the CLI project generator.
// CLI uses console.log intentionally — not subject to AGENTS.md production logging rule.
//
// The generated project is a STANDALONE plugin repository: it must build and
// run outside the Plexica monorepo. Keep these templates coherent with the
// CRM example (examples/plugins/crm) and with @plexica/vite-plugin's
// manifest mapping (ui.extensionPoints → ./ui/<point>.tsx).

export const TEMPLATES: Record<string, string> = {
  '.gitignore': `node_modules\ndist\ndist-ui\n.env\n*.local\n`,
  '.npmrc': `# @plexica/* are published to GitHub Packages (ADR-033).\n# The registry scope alone is safe to commit; the auth token must NOT be\n# committed here — pnpm (>=10.34.2) ignores env placeholders in project\n# .npmrc. Configure the token at USER level instead:\n#   pnpm config set //npm.pkg.github.com/:_authToken <GH_TOKEN> --location user\n@plexica:registry=https://npm.pkg.github.com/\n`,
  'manifest.json': `{\n  "slug": "{{slug}}",\n  "name": "{{name}}",\n  "version": "1.0.0",\n  "description": "A Plexica plugin",\n  "author": "Plugin Author",\n  "icon": "Package",\n  "categories": [],\n  "hosting": {\n    "type": "sidecar",\n    "image": "{{slug}}:latest",\n    "port": 3000\n  },\n  "ui": {\n    "remoteEntry": "remoteEntry.js",\n    "extensionPoints": ["sidebar:admin"]\n  },\n  "events": {\n    "subscribes": []\n  },\n  "declaredTables": []\n}\n`,
  'vite.config.ts': `import { defineConfig } from 'vite';\nimport react from '@vitejs/plugin-react';\nimport plexicaPlugin from '@plexica/vite-plugin';\n\nexport default defineConfig({\n  plugins: [react(), ...plexicaPlugin({ manifestPath: './manifest.json' })],\n  build: {\n    target: 'es2022',\n    modulePreload: false,\n    cssCodeSplit: false,\n    outDir: 'dist-ui',\n    rollupOptions: { input: 'ui/index.ts' },\n  },\n  server: { port: 4001, cors: true },\n  preview: { port: 4001, cors: true },\n});\n`,
  'package.json': `{\n  "name": "{{slug}}",\n  "version": "1.0.0",\n  "private": true,\n  "type": "module",\n  "scripts": {\n    "dev": "concurrently -n backend,ui,reg -c blue,magenta,cyan \\"tsx watch --env-file-if-exists=.env.development src/index.ts\\" \\"vite dev --port 4001\\" \\"tsx --env-file-if-exists=.env.development dev-entry.ts\\"",\n    "dev:backend": "tsx watch --env-file-if-exists=.env.development src/index.ts",\n    "dev:ui": "vite dev --port 4001",\n    "build": "pnpm build:backend && pnpm build:ui",\n    "build:backend": "tsc",\n    "build:ui": "vite build",\n    "start": "node dist/index.js",\n    "typecheck": "tsc --noEmit && tsc --noEmit -p tsconfig.ui.json && tsc --noEmit -p tsconfig.dev.json"\n  },\n  "dependencies": {\n    "@plexica/sdk": "^0.1.0",\n    "@plexica/ui": "^0.0.1",\n    "@tanstack/react-query": "^5.0.0",\n    "fastify": "^5.12.0",\n    "react": "^19.2.0",\n    "react-dom": "^19.2.0",\n    "react-intl": "^6.6.0"\n  },\n  "devDependencies": {\n    "@originjs/vite-plugin-federation": "^1.4.1",\n    "@plexica/vite-plugin": "^0.1.0",\n    "@types/node": "^24.0.0",\n    "@types/react": "^19.2.0",\n    "@types/react-dom": "^19.2.0",\n    "@vitejs/plugin-react": "^4.3.0",\n    "concurrently": "^9.2.0",\n    "tsx": "^4.23.0",\n    "typescript": "^5.9.0",\n    "vite": "^6.4.0"\n  }\n}\n`,
  'tsconfig.json': `{\n  "compilerOptions": {\n    "target": "ES2022",\n    "module": "ESNext",\n    "moduleResolution": "bundler",\n    "strict": true,\n    "jsx": "react-jsx",\n    "outDir": "dist",\n    "rootDir": "src",\n    "esModuleInterop": true,\n    "skipLibCheck": true,\n    "declaration": true\n  },\n  "include": ["src"]\n}\n`,
  'tsconfig.dev.json': `{\n  "compilerOptions": {\n    "target": "ES2022",\n    "module": "ESNext",\n    "moduleResolution": "bundler",\n    "strict": true,\n    "esModuleInterop": true,\n    "skipLibCheck": true,\n    "noEmit": true,\n    "types": ["node"]\n  },\n  "include": ["dev-entry.ts"]\n}\n`,
  'tsconfig.ui.json': `{\n  "compilerOptions": {\n    "target": "ES2022",\n    "module": "ESNext",\n    "moduleResolution": "bundler",\n    "strict": true,\n    "jsx": "react-jsx",\n    "noEmit": true\n  },\n  "include": ["ui"]\n}\n`,
  'Dockerfile': `# syntax=docker/dockerfile:1.7\nFROM node:24-alpine\nRUN corepack enable\nWORKDIR /app\n# .npmrc ships the @plexica registry scope (no token). Mount a user-level\n# .npmrc as a BuildKit secret when GH Packages needs credentials:\n#   docker build --secret id=npmrc,src=$HOME/.npmrc .\nCOPY package.json .npmrc ./\nRUN --mount=type=secret,id=npmrc,target=/root/.npmrc pnpm install --no-frozen-lockfile\nCOPY . .\nRUN pnpm build\nEXPOSE 3000\nCMD ["node", "dist/index.js"]\n`,
  '.dockerignore': `node_modules\ndist\ndist-ui\n.env\n.git\n*.local\n`,
  'src/index.ts': `import Fastify from 'fastify';\n\nimport { pluginRoutes } from './app.js';\n\nconst server = Fastify({ logger: true });\nconst port = Number(process.env['PORT']) || 3000;\n\nserver.get('/_plexica/health', async () => ({ status: 'healthy', version: '1.0.0' }));\nserver.get('/_plexica/ready', async () => ({ status: 'ready' }));\nserver.post('/_plexica/event', async () => ({ received: true }));\n\nawait server.register(pluginRoutes);\n\nawait server.listen({ port, host: '0.0.0.0' });\n`,
  'src/app.ts': `import type { FastifyInstance } from 'fastify';\n\nexport async function pluginRoutes(app: FastifyInstance): Promise<void> {\n  app.get('/hello', async () => ({ message: 'Hello from {{name}}!' }));\n}\n`,
  'ui/index.ts': `export { default } from './sidebar-admin';\n`,
  'ui/sidebar-admin.tsx': `// Rendered in the host shell at the "sidebar:admin" extension point\n// (mapped by @plexica/vite-plugin from manifest.json ui.extensionPoints).\nimport type { JSX } from 'react';\nimport { useIntl } from 'react-intl';\n\nexport default function SidebarAdmin(): JSX.Element {\n  const intl = useIntl();\n  return (\n    <div className="p-4">\n      <h2 className="text-lg font-semibold">{{name}}</h2>\n      <p className="text-neutral-600">\n        {intl.formatMessage({ id: 'plugin.active', defaultMessage: 'Plugin is active.' })}\n      </p>\n    </div>\n  );\n}\n`,
  'migrations/001_create_tables.sql': `-- CREATE TABLE IF NOT EXISTS {{slug}}_items (\n--   id UUID PRIMARY KEY DEFAULT gen_random_uuid(),\n--   name TEXT NOT NULL,\n--   created_at TIMESTAMPTZ DEFAULT now()\n-- );\n`,
  'dev-entry.ts': `// Dev-mode registration: tells the local core API where this plugin runs.\n// Requires the platform to be up (docker compose up) and NODE_ENV=development.\n\nimport { registerBackend, unregisterBackend } from '@plexica/sdk/dev';\n\nconst CORE_API_URL = process.env['CORE_API_URL'] ?? 'http://localhost:3001';\nconst SLUG = '{{slug}}';\nconst TENANT_SLUG = process.env['TENANT_SLUG'] ?? '';\nconst BACKEND_URL = process.env['BACKEND_URL'] ?? 'http://localhost:3000';\nconst UI_URL = process.env['UI_URL'] ?? 'http://localhost:4001/remoteEntry.js';\n\nasync function main() {\n  if (!TENANT_SLUG) {\n    console.warn('TENANT_SLUG is not set — set it in .env.development to register the plugin');\n    process.exitCode = 1;\n    return;\n  }\n\n  // Track SIGINT/SIGTERM that arrive while registration is pending (CodeRabbit): if\n  // the process is terminated after Core stores the entry but before the\n  // response returns, the next start would see 409.\n  let pendingSignal: string | null = null;\n  const onPendingSignal = (sig: string): void => { pendingSignal = sig; };\n  process.on('SIGINT', onPendingSignal);\n  process.on('SIGTERM', onPendingSignal);\n\n  console.log('Registering plugin with core API...');\n  const res = await registerBackend(CORE_API_URL, {\n    slug: SLUG,\n    tenantSlug: TENANT_SLUG,\n    backendUrl: BACKEND_URL,\n    uiUrl: UI_URL,\n    extensionPoints: ['sidebar:admin'],\n  });\n  if (!res.ok) {\n    const body = await res.text();\n    console.warn('Failed to register — is the platform running?', res.status, body);\n    process.exitCode = 1;\n    process.off('SIGINT', onPendingSignal);\n    process.off('SIGTERM', onPendingSignal);\n    return;\n  }\n  console.log('Plugin registered with core API');\n\n  // Replace pending handlers with real cleanup (only after successful registration).\n  process.off('SIGINT', onPendingSignal);\n  process.off('SIGTERM', onPendingSignal);\n  if (pendingSignal) {\n    console.log(\`Received \${pendingSignal} while registering — unregistering plugin...\`);\n    await unregisterBackend(CORE_API_URL, { slug: SLUG, tenantSlug: TENANT_SLUG });\n    process.exit(0);\n    return;\n  }\n\n  let cleanedUp = false;\n  async function cleanup(signal: string): Promise<void> {\n    if (cleanedUp) return;\n    cleanedUp = true;\n    try {\n      console.log(\`Received \${signal} — unregistering plugin...\`);\n      await unregisterBackend(CORE_API_URL, { slug: SLUG, tenantSlug: TENANT_SLUG });\n    } finally {\n      // Guarantee termination even if unregisterBackend rejects (CodeRabbit).\n      process.exit(0);\n    }\n  }\n  process.on('SIGINT', () => void cleanup('SIGINT'));\n  process.on('SIGTERM', () => void cleanup('SIGTERM'));\n}\n\nmain().catch((error) => {\n  console.error(error);\n  process.exitCode = 1;\n});\n`,
  '.env.development': `CORE_API_URL=http://localhost:3001\nTENANT_SLUG=\n`,
};

export function render(template: string, slug: string, name: string): string {
  return template.replace(/\{\{slug\}\}/g, slug).replace(/\{\{name\}\}/g, name);
}