// templates.ts
// Handlebars-style templates for the CLI project generator.
// CLI uses console.log intentionally — not subject to AGENTS.md production logging rule.

export const TEMPLATES: Record<string, string> = {
  'manifest.json': `{\n  "slug": "{{slug}}",\n  "name": "{{name}}",\n  "version": "1.0.0",\n  "description": "A Plexica plugin",\n  "author": "",\n  "categories": [],\n  "hosting": {\n    "type": "sidecar",\n    "image": "{{slug}}:latest",\n    "port": 3000\n  },\n  "ui": {\n    "remoteEntry": "remoteEntry.js",\n    "extensionPoints": ["sidebar:admin"]\n  },\n  "events": {\n    "subscribes": ["plexica.workspace.*"]\n  },\n  "declaredTables": []\n}\n`,
  'vite.config.ts': `import { defineConfig } from 'vite';\nimport plexicaPlugin from '@plexica/vite-plugin';\n\nexport default defineConfig({\n  plugins: [plexicaPlugin()],\n  server: { port: 4001 },\n  build: { target: 'es2022' },\n});\n`,
  'package.json': `{\n  "name": "{{slug}}",\n  "version": "1.0.0",\n  "private": true,\n  "type": "module",\n  "scripts": {\n    "dev": "tsx dev-entry.ts",\n    "dev:backend": "tsx watch src/index.ts",\n    "dev:ui": "vite dev --port 4001",\n    "build": "vite build && tsc"\n  },\n  "dependencies": {\n    "@plexica/sdk": "^0.1.0",\n    "@plexica/vite-plugin": "^0.1.0",\n    "fastify": "^5.0.0"\n  },\n  "devDependencies": {\n    "typescript": "^5.9.0",\n    "vite": "^6.0.0",\n    "tsx": "^4.0.0"\n  }\n}\n`,
  'tsconfig.json': `{\n  "compilerOptions": {\n    "target": "ES2022",\n    "module": "ESNext",\n    "moduleResolution": "bundler",\n    "strict": true,\n    "jsx": "react-jsx",\n    "outDir": "dist"\n  },\n  "include": ["src"]\n}\n`,
  'Dockerfile': `FROM node:24-alpine\nRUN corepack enable\nWORKDIR /app\nCOPY package.json pnpm-lock.yaml ./\nRUN pnpm install --frozen-lockfile\nCOPY . .\nRUN pnpm build\nEXPOSE 3000\nCMD ["node", "dist/index.js"]\n`,
  'src/index.ts': `import Fastify from 'fastify';\n\nconst server = Fastify({ logger: true });\n\nserver.get('/_plexica/health', async () => ({ status: 'healthy', version: '1.0.0' }));\nserver.get('/_plexica/ready', async () => ({ status: 'ready' }));\n\nserver.listen({ port: 3000, host: '0.0.0.0' });\n`,
  'src/app.ts': `import type { FastifyInstance } from 'fastify';\n\nexport async function pluginRoutes(app: FastifyInstance): Promise<void> {\n  app.get('/hello', async () => ({ message: 'Hello from plugin!' }));\n}\n`,
  'src/health.ts': `import type { FastifyInstance } from 'fastify';\n\nexport async function healthRoutes(app: FastifyInstance): Promise<void> {\n  app.get('/_plexica/health', async () => ({ status: 'healthy', version: '1.0.0' }));\n  app.get('/_plexica/ready', async () => ({ status: 'ready' }));\n  app.post('/_plexica/event', async (request) => {\n    return { received: true };\n  });\n}\n`,
  'ui/index.ts': `export { default as PluginComponent } from './PluginComponent';\n`,
  'ui/PluginComponent.tsx': `import React from 'react';\n\nexport default function PluginComponent(): JSX.Element {\n  return (\n    <div className="p-4">\n      <h2 className="text-lg font-semibold">{{name}}</h2>\n      <p className="text-neutral-600">Plugin is active.</p>\n    </div>\n  );\n}\n`,
  'migrations/001_create_tables.sql': `-- CREATE TABLE IF NOT EXISTS {{slug}}_items (\n--   id UUID PRIMARY KEY DEFAULT gen_random_uuid(),\n--   name TEXT NOT NULL,\n--   created_at TIMESTAMPTZ DEFAULT now()\n-- );\n`,
  'dev-entry.ts': `import { registerBackend } from '@plexica/sdk/dev';\n\nconst CORE_API_URL = process.env['CORE_API_URL'] ?? 'http://localhost:3001';\n\nasync function main() {\n  console.log('Starting plugin dev mode...');\n  const res = await registerBackend(CORE_API_URL, {\n    slug: '{{slug}}',\n    backendUrl: 'http://localhost:4002',\n    uiUrl: 'http://localhost:4001/remoteEntry.js',\n    extensionPoints: ['sidebar:admin'],\n  });\n  if (res.ok) {\n    console.log('Plugin registered with core API');\n  } else {\n    console.warn('Failed to register — make sure the platform is running');\n  }\n  process.on('SIGINT', async () => {\n    await fetch(\`\${CORE_API_URL}/api/v1/dev/plugins/unregister\`, {\n      method: 'POST',\n      headers: { 'Content-Type': 'application/json' },\n      body: JSON.stringify({ slug: '{{slug}}' }),\n    });\n    process.exit(0);\n  });\n}\nmain().catch(console.error);\n`,
  'dev-register.ts': `export async function registerDevPlugin(\n  coreApiUrl: string, slug: string, backendUrl: string\n): Promise<Response> {\n  return fetch(\`\${coreApiUrl}/api/v1/dev/plugins/register\`, {\n    method: 'POST',\n    headers: { 'Content-Type': 'application/json' },\n    body: JSON.stringify({ slug, backendUrl }),\n  });\n}\n\nexport async function unregisterDevPlugin(\n  coreApiUrl: string, slug: string\n): Promise<Response> {\n  return fetch(\`\${coreApiUrl}/api/v1/dev/plugins/unregister\`, {\n    method: 'POST',\n    headers: { 'Content-Type': 'application/json' },\n    body: JSON.stringify({ slug }),\n  });\n}\n`,
  '.env.development': `CORE_API_URL=http://localhost:3001\nKAFKA_BROKERS=localhost:9092\nDATABASE_URL=postgresql://localhost:5432/plexica?schema=tenant_dev\n`,
};

export function render(template: string, slug: string, name: string): string {
  return template.replace(/\{\{slug\}\}/g, slug).replace(/\{\{name\}\}/g, name);
}
