import { spawnSync } from 'node:child_process';
import { fileURLToPath, URL } from 'node:url';

const script = fileURLToPath(new URL('./ci-runtime-endpoint-contract.mjs', import.meta.url));

function accepts(key, value) {
  return spawnSync(process.execPath, [script, 'host', key, value]).status === 0;
}

function acceptsContainer(key, value) {
  return spawnSync(process.execPath, [script, 'container', key, value]).status === 0;
}

if (!accepts('POSTGRES_HOST_URL', 'postgresql://user:password@127.0.0.1:32123/plexica')) {
  throw new Error('Credentialed inspected PostgreSQL host URL was rejected');
}
// Host-manifest credential scalars (provisioning CLI contract): hex values
// generated by the CI bootstrap and workflow must both be accepted.
for (const [key, value] of [
  ['MINIO_ACCESS_KEY', '00112233445566778899aabb'],
  ['MINIO_SECRET_KEY', '00112233445566778899aabbccddeeff00112233445566778899aabbccddeeff'],
]) {
  if (!accepts(key, value)) throw new Error(`Rejected approved host credential scalar ${key}`);
}
if (accepts('MINIO_SECRET_KEY', '')) {
  throw new Error('Accepted an empty MinIO secret key');
}
// Host TLS contract is fail-closed: runner CLIs run NODE_ENV development/test,
// so only an explicit disable may pass host-kind validation; verify-full is
// production-only and belongs to container.env.
if (!accepts('PLUGIN_DB_SSL_MODE', 'disable')) {
  throw new Error('Rejected approved host TLS scalar PLUGIN_DB_SSL_MODE');
}
for (const [key, value] of [
  ['PLUGIN_DB_SSL_MODE', ''],
  ['PLUGIN_DB_SSL_MODE', 'prefer'],
  ['PLUGIN_DB_SSL_MODE', 'require'],
  ['PLUGIN_DB_SSL_MODE', 'verify-full'],
  ['PLUGIN_DB_SSL_MODE', 'verify-ca'],
  // The CA path is a container-only key: host-kind validation rejects it
  // entirely because runner CLIs never open plugin TLS connections.
  ['PLUGIN_DB_SSL_ROOT_CERT_PATH', '/run/plexica-ci/postgres-ca.crt'],
  ['PLUGIN_DB_SSL_ROOT_CERT_PATH', '/etc/ssl/certs/ca-certificates.crt'],
  ['PLUGIN_DB_SSL_ROOT_CERT_PATH', '/etc/ssl/certs/evil.pem'],
  ['PLUGIN_DB_SSL_ROOT_CERT_PATH', ''],
]) {
  if (accepts(key, value)) throw new Error(`Accepted invalid host TLS contract for ${key}: ${value}`);
}
for (const [key, value] of [
  ['CI_RUNTIME_CONTRACT_CONTAINER', '1'],
  ['KAFKA_BROKERS', 'redpanda:9092'],
  ['PLUGIN_DB_SSL_MODE', 'verify-full'],
  // Only the mounted project CA path is admitted: the host system bundle
  // lacks the E2E Postgres CA and must never be trusted by containers.
  ['PLUGIN_DB_SSL_ROOT_CERT_PATH', '/run/plexica-ci/postgres-ca.crt'],
  ['CI_RUNTIME_CA_FILE', '/run/plexica-ci/postgres-ca.crt'],
  ['PLUGIN_RUNTIME_SCOPE', 'ci-0123456789abcdef0123456789ab'],
  ['KEYCLOAK_ADMIN_PASSWORD', 'not-a-url'],
  ['EVENT_KEY_ENCRYPTION_KEY', 'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA'],
  ['PLUGIN_DB_ENCRYPTION_KEY', 'aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa'],
  ['PLUGIN_CREDENTIAL_PEPPER', '0123456789abcdef0123456789abcdef'],
]) {
  if (!acceptsContainer(key, value)) throw new Error(`Rejected approved scalar contract ${key}`);
}
for (const key of ['PLUGIN_DB_SSL_ROOT_CERT_PATH', 'CI_RUNTIME_CA_FILE']) {
  for (const value of [
    '/etc/ssl/certs/ca-certificates.crt',
    '/etc/ssl/certs/evil.pem',
    '/run/plexica-ci/../plexica-ci/postgres-ca.crt',
    '/run/plexica-ci/postgres-ca.pem',
    '',
  ]) {
    if (acceptsContainer(key, value)) {
      throw new Error(`Accepted non-project CA path for ${key}: ${value}`);
    }
  }
}
if (acceptsContainer('KAFKA_BROKERS', 'http://redpanda:9092')) {
  throw new Error('Accepted a URL where the Kafka scalar contract is required');
}
for (const value of ['', '0', 'true', 'yes']) {
  if (acceptsContainer('CI_RUNTIME_CONTRACT_CONTAINER', value)) {
    throw new Error(`Accepted invalid container marker CI_RUNTIME_CONTRACT_CONTAINER=${value}`);
  }
}
// Every per-key Compose DNS service endpoint must be accepted verbatim.
for (const [key, value] of [
  ['DATABASE_URL', 'postgresql://plexica:secret@postgres:5432/plexica'],
  ['KEYCLOAK_URL', 'http://keycloak:8080'],
  ['KEYCLOAK_CONTAINER_ADMIN_JWKS_BASE', 'http://keycloak:8080'],
  ['REDIS_URL', 'redis://redis:6379'],
  ['MINIO_ENDPOINT', 'http://minio:9000'],
  ['LOKI_URL', 'http://loki:3100'],
  ['PLUGIN_CORE_API_URL', 'http://core-api-e2e:3001'],
]) {
  if (!acceptsContainer(key, value)) throw new Error(`Rejected approved Compose DNS endpoint ${key}`);
}
// Parsed-URL hardening: host forms outside the per-key allowlist must be
// rejected regardless of case, brackets, ports or credentials.
for (const [key, value] of [
  ['KEYCLOAK_URL', 'http://HOST.DOCKER.INTERNAL:8080'],
  ['KEYCLOAK_URL', 'http://host.docker.internal:8080'],
  ['KEYCLOAK_URL', 'http://x.host.docker.internal:8080'],
  ['KEYCLOAK_URL', 'http://localhost'],
  ['KEYCLOAK_URL', 'http://localhost:8080'],
  ['KEYCLOAK_URL', 'http://LOCALHOST:8080'],
  ['KEYCLOAK_URL', 'http://0.0.0.0:8080'],
  ['KEYCLOAK_URL', 'http://127.0.0.1:8080'],
  ['KEYCLOAK_URL', 'http://10.0.0.5:8080'],
  ['KEYCLOAK_URL', 'http://192.168.1.14:8080'],
  ['KEYCLOAK_URL', 'http://[::1]:8080'],
  ['KEYCLOAK_URL', 'http://[::]:8080'],
  ['KEYCLOAK_URL', 'http://[fe80::1]:8080'],
  ['KEYCLOAK_URL', 'http://::1:8080'],
  ['KEYCLOAK_URL', 'http://keycloak.evil.test:8080'],
  ['KEYCLOAK_URL', 'http://redis:8080'],
  ['KEYCLOAK_URL', 'https://keycloak:8080'],
  ['KEYCLOAK_URL', 'host-gateway://keycloak:8080'],
  ['PLUGIN_CORE_API_URL', 'http://web-e2e:3000'],
  ['PLUGIN_CORE_API_URL', 'ftp://core-api-e2e:3001'],
  ['DATABASE_URL', 'http://postgres:5432/plexica'],
  ['MINIO_ENDPOINT', 'http://keycloak:9000'],
]) {
  if (acceptsContainer(key, value)) throw new Error(`Accepted non-Compose container endpoint for ${key}: ${value}`);
}
for (const [key, value] of [
  ['POSTGRES_HOST_URL', 'postgresql://user@127.0.0.1:32123/plexica'],
  ['POSTGRES_HOST_URL', 'postgresql://user:password@postgres:5432/plexica'],
  ['REDIS_HOST_URL', 'redis://user:password@127.0.0.1:32123'],
  ['KEYCLOAK_HOST_ADMIN_BASE', 'http://user:password@127.0.0.1:32123'],
]) {
  if (accepts(key, value)) throw new Error(`Accepted unsafe host endpoint for ${key}`);
}
